services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://*:5000
    volumes:
      - ./backend/src:/app
      - /app/Api/obj/
      - /app/Api/bin/
      - /app/Application/obj/
      - /app/Application/bin/
      - /app/Domain/obj/
      - /app/Domain/bin/
      - /app/Infrastructure/obj/
      - /app/Infrastructure/bin/
      - /app/Persistence/obj/
      - /app/Persistence/bin/
      - /app/SharedKernel/obj/
      - /app/SharedKernel/bin/
    ports:
      - 5000:5000
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: my-multi-project
    volumes:
      - ./.containers/db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pgadmin4:
    image: dpage/pgadmin4:9
    container_name: pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - ./.containers/pgadmin:/var/lib/pgadmin
    ports:
      - 5050:80
    depends_on:
      - postgres
